-- begin PMSSTART_NEXTOFKIN
alter table PMSSTART_NEXTOFKIN add constraint FK_PMSSTART_NEXTOFKIN_ON_PRISONERDETAILS foreign key (PRISONERDETAILS_ID) references PMSSTART_PRISONERDETAILS(ID)^
create index IDX_PMSSTART_NEXTOFKIN_ON_PRISONERDETAILS on PMSSTART_NEXTOFKIN (PRISONERDETAILS_ID)^
-- end PMSSTART_NEXTOFKIN
-- begin PMSSTART_FOREIGNADDRESS
alter table PMSSTART_FOREIGNADDRESS add constraint FK_PMSSTART_FOREIGNADDRESS_ON_PRISONERDETAILS foreign key (PRISONERDETAILS_ID) references PMSSTART_PRISONERDETAILS(ID)^
create index IDX_PMSSTART_FOREIGNADDRESS_ON_PRISONERDETAILS on PMSSTART_FOREIGNADDRESS (PRISONERDETAILS_ID)^
-- end PMSSTART_FOREIGNADDRESS
-- begin PMSSTART_SENTENCEDETAILS
alter table PMSSTART_SENTENCEDETAILS add constraint FK_PMSSTART_SENTENCEDETAILS_ON_PRISONERDETAILS foreign key (PRISONERDETAILS_ID) references PMSSTART_PRISONERDETAILS(ID)^
create index IDX_PMSSTART_SENTENCEDETAILS_ON_PRISONERDETAILS on PMSSTART_SENTENCEDETAILS (PRISONERDETAILS_ID)^
-- end PMSSTART_SENTENCEDETAILS
