-- begin PMSSTART_NEXTOFKIN
alter table PMSSTART_NEXTOFKIN add constraint FK_PMSSTART_NEXTOFKIN_ON_PRISONERDETAILS foreign key (PRISONERDETAILS_ID) references PMSSTART_PRISONERDETAILS(ID)^
create index IDX_PMSSTART_NEXTOFKIN_ON_PRISONERDETAILS on PMSSTART_NEXTOFKIN (PRISONERDETAILS_ID)^
-- end PMSSTART_NEXTOFKIN
