-- begin PMSSTART_NEXTOFKIN
alter table PMSSTART_NEXTOFKIN add constraint FK_PMSSTART_NEXTOFKIN_ON_PRISONERDETAILS foreign key (PRISONERDETAILS_ID) references PMSSTART_PRISONERDETAILS(ID)^
create index IDX_PMSSTART_NEXTOFKIN_ON_PRISONERDETAILS on PMSSTART_NEXTOFKIN (PRISONERDETAILS_ID)^
-- end PMSSTART_NEXTOFKIN
-- begin PMSSTART_FOREIGNADDRESS
alter table PMSSTART_FOREIGNADDRESS add constraint FK_PMSSTART_FOREIGNADDRESS_ON_PRISONERDETAILS foreign key (PRISONERDETAILS_ID) references PMSSTART_PRISONERDETAILS(ID)^
create index IDX_PMSSTART_FOREIGNADDRESS_ON_PRISONERDETAILS on PMSSTART_FOREIGNADDRESS (PRISONERDETAILS_ID)^
-- end PMSSTART_FOREIGNADDRESS
-- begin PMSSTART_SENTENCEDETAILS
alter table PMSSTART_SENTENCEDETAILS add constraint FK_PMSSTART_SENTENCEDETAILS_ON_PRISONERDETAILS foreign key (PRISONERDETAILS_ID) references PMSSTART_PRISONERDETAILS(ID)^
create index IDX_PMSSTART_SENTENCEDETAILS_ON_PRISONERDETAILS on PMSSTART_SENTENCEDETAILS (PRISONERDETAILS_ID)^
-- end PMSSTART_SENTENCEDETAILS
-- begin PMSSTART_BIOMETRIC
alter table PMSSTART_BIOMETRIC add constraint FK_PMSSTART_BIOMETRIC_ON_PRISONERDETAILS foreign key (PRISONERDETAILS_ID) references PMSSTART_PRISONERDETAILS(ID)^
create index IDX_PMSSTART_BIOMETRIC_ON_PRISONERDETAILS on PMSSTART_BIOMETRIC (PRISONERDETAILS_ID)^
-- end PMSSTART_BIOMETRIC
-- begin PMSSTART_MEDICALINFORMATION
alter table PMSSTART_MEDICALINFORMATION add constraint FK_PMSSTART_MEDICALINFORMATION_ON_BIOMETRIC foreign key (BIOMETRIC_ID) references PMSSTART_BIOMETRIC(ID)^
create index IDX_PMSSTART_MEDICALINFORMATION_ON_BIOMETRIC on PMSSTART_MEDICALINFORMATION (BIOMETRIC_ID)^
-- end PMSSTART_MEDICALINFORMATION
